# play 1
- name: Configure the webservers
  hosts: webservers
  # Bring in role users, execute, then move on to tasks
  roles:
    - users
  tasks:
    # - name: Create a non-root user
    #   user:
    #     name: tjsoderl
    #     state: present
    - name: Install nginx
      package:
        name: nginx
        state: present
- name: Configure the databases
  hosts: databases
  tasks:
    - name: Install MySQL Server
      package:
        name: mysql-server
        state: present
